context:
  version: "1.4.10"

package:
  name: ini-file
  version: ${{ version }}

source:
  url: https://github.com/bitnami/ini-file/archive/refs/tags/v${{ version }}.tar.gz
  sha256: eb4cc92095f27f0d6cb1a091a53b539deab5d2998ba4a736756fb2cabd7213cb

build:
  number: 0
  script:
    interpreter: nu
    content:
      - let prefix = $env.LIBRARY_PREFIX? | default $env.PREFIX
      # build main app and generate license data
      - let build_time = date now | format date "%Y-%m-%dT%H:%M:%SZ"
      - let short_commit_hash = (http get https://api.github.com/repos/bitnami/ini-file/commits/v${{ version }}).sha | str substring 0..6
      - go build
        -o ($prefix)/bin/
        -v
        -ldflags=$'-s -w -X main.buildDate=($build_time) -X main.commit=($short_commit_hash) -X main.version=${{ version }}'
        -trimpath
        .
      - go-licenses save . --save_path=library_licenses

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses
    - nushell

tests:
  - script:
      - if: win
        then: ini-file --help 2>&1 | findstr /c:"Usage:" >nul
      - if: unix
        then: ini-file --help 2>&1 | grep -q "Usage:"
  - package_contents:
      bin:
        - ini-file
      strict: true

about:
  summary: A CLI tool for manipulating INI files
  description: |
    ini-file is a command-line tool that allows manipulating INI files.
    It supports setting, getting, and deleting values in INI files.
  license: Apache-2.0
  license_file:
    - LICENSE.md
    - library_licenses/
  homepage: https://github.com/bitnami/ini-file
  repository: https://github.com/bitnami/ini-file

extra:
  recipe-maintainers:
    - salim-b
